name: vast_world
description: The package for work with huge worlds.
publish_to: none

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  advance_math: ^3.3.7
  astronomical_measurements:
    path: ../astronomical_measurements
  collection: ^1.18.0
  dart_helpers:
    path: ../dart_helpers
  dart_tiledmap:
    path: ../dart_tiledmap
  id_gen:
    path: ../id_gen
  image: ^4.1.3
  meta: ^1.11.0
  oxygen: ^0.2.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
